// Generated by BUCKLESCRIPT VERSION 5.0.1, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactLeaflet from "react-leaflet";

function s(prim) {
  return prim;
}

function App(Props) {
  return React.createElement("div", {
              style: {
                height: "98vh"
              }
            }, React.createElement(ReactLeaflet.Map, {
                  center: /* tuple */[
                    51,
                    0.9
                  ],
                  zoom: 13,
                  children: React.createElement(ReactLeaflet.TileLayer, {
                        url: "http://{s}.tile.osm.org/{z}/{x}/{y}.png",
                        attribution: "&copy; <a href='http://osm.org/copyright'>OpenStreetMap</a> contributors"
                      })
                }));
}

var make = App;

export {
  s ,
  make ,
  
}
/* react Not a pure module */
