// Generated by BUCKLESCRIPT VERSION 5.0.1, PLEASE EDIT WITH CARE

import * as List from "bs-platform/lib/es6/list.js";
import * as $$Array from "bs-platform/lib/es6/array.js";
import * as Block from "bs-platform/lib/es6/block.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ReactLeaflet from "react-leaflet";

function reducer(state, action) {
  if (action.tag) {
    var id = action[0];
    return List.filter((function (marker) {
                    return marker[/* id */0] !== id;
                  }))(state);
  } else {
    var match = action[0];
    var y = match[1];
    var x = match[0];
    return /* :: */[
            /* record */[
              /* id */"" + (String(x) + (":" + (String(y) + ""))),
              /* position : tuple */[
                x,
                y
              ]
            ],
            state
          ];
  }
}

function App(Props) {
  var match = Props.initialMarkers;
  var initialMarkers = match !== undefined ? match : /* [] */0;
  var match$1 = React.useReducer(reducer, initialMarkers);
  var dispatch = match$1[1];
  return React.createElement(ReactLeaflet.Map, {
              center: /* tuple */[
                0.0,
                0.0
              ],
              zoom: 5,
              onClick: (function (e) {
                  return Curry._1(dispatch, /* AddMarker */Block.__(0, [/* tuple */[
                                  e.latlng.lat,
                                  e.latlng.lng
                                ]]));
                }),
              children: null
            }, React.createElement(ReactLeaflet.TileLayer, {
                  url: "http://{s}.tile.osm.org/{z}/{x}/{y}.png",
                  attribution: "&copy; <a href='http://osm.org/copyright'>OpenStreetMap</a> contributors"
                }), $$Array.of_list(List.map((function (marker) {
                        return React.createElement(ReactLeaflet.Marker, {
                                    position: marker[/* position */1],
                                    onClick: (function (param) {
                                        return Curry._1(dispatch, /* RemoveMarker */Block.__(1, [marker[/* id */0]]));
                                      }),
                                    key: marker[/* id */0]
                                  });
                      }), match$1[0])));
}

var make = App;

export {
  reducer ,
  make ,
  
}
/* react Not a pure module */
