// Generated by BUCKLESCRIPT VERSION 5.0.1, PLEASE EDIT WITH CARE

import * as List from "bs-platform/lib/es6/list.js";
import * as $$Array from "bs-platform/lib/es6/array.js";
import * as React from "react";
import * as ReactLeaflet from "react-leaflet";
import * as Data$ReactTemplate from "./Data.bs.js";

function s(prim) {
  return prim;
}

function a(prim) {
  return prim;
}

function coordToPos(param) {
  return /* tuple */[
          param[/* lat */0],
          param[/* lng */1]
        ];
}

function App(Props) {
  var markers = $$Array.of_list(List.map((function (x) {
              return React.createElement(ReactLeaflet.Marker, {
                          position: coordToPos(x[/* coordinates */2]),
                          children: React.createElement(ReactLeaflet.Popup, {
                                children: null
                              }, React.createElement("span", undefined, x[/* name */1]), React.createElement("img", {
                                    src: x[/* image */3][/* url */0],
                                    width: "300px"
                                  })),
                          key: x[/* id */0]
                        });
            }), Data$ReactTemplate.cities));
  return React.createElement("div", {
              style: {
                height: "98vh"
              }
            }, React.createElement(ReactLeaflet.Map, {
                  center: coordToPos(List.hd(Data$ReactTemplate.cities)[/* coordinates */2]),
                  zoom: 13,
                  children: null
                }, React.createElement(ReactLeaflet.TileLayer, {
                      url: "http://{s}.tile.osm.org/{z}/{x}/{y}.png",
                      attribution: "&copy; <a href='http://osm.org/copyright'>OpenStreetMap</a> contributors"
                    }), markers));
}

var make = App;

export {
  s ,
  a ,
  coordToPos ,
  make ,
  
}
/* react Not a pure module */
