// Generated by BUCKLESCRIPT VERSION 5.0.1, PLEASE EDIT WITH CARE

import * as Emotion from "bs-emotion/src/Emotion.bs.js";

Emotion.$$global("html", /* :: */[
      Emotion.fontFamily("'Arvo', serif"),
      /* :: */[
        Emotion.fontSize(/* `px */[
              25096,
              28
            ]),
        /* :: */[
          Emotion.lineHeight(/* `em */[
                22632,
                1.15
              ]),
          /* [] */0
        ]
      ]
    ]);

Emotion.$$global("ul", /* :: */[
      Emotion.padding(/* `px */[
            25096,
            0
          ]),
      /* :: */[
        Emotion.listStyleType(/* none */-922086728),
        /* [] */0
      ]
    ]);

Emotion.$$global(".leaflet-container", /* :: */[
      Emotion.width(/* `vw */[
            26433,
            90.0
          ]),
      /* :: */[
        Emotion.height(/* `vh */[
              26418,
              90.0
            ]),
        /* [] */0
      ]
    ]);

Emotion.$$global(".img", /* :: */[
      Emotion.width(/* `vw */[
            26433,
            20.0
          ]),
      /* :: */[
        Emotion.height(/* `vh */[
              26418,
              20.0
            ]),
        /* [] */0
      ]
    ]);

export {
  
}
/*  Not a pure module */
